INSERT INTO tb_plano (NUMEROANS, COPARTICIPACAO, DESCRICAO, VALOR_INICIAL) VALUES (123, 1, 'Plano Basico com Copoarticipacao', 300.0);
INSERT INTO tb_plano (NUMEROANS, COPARTICIPACAO, DESCRICAO, VALOR_INICIAL) VALUES (456, 0, 'Plano Basico Pleno', 500.0);
INSERT INTO tb_cliente (CARTEIRINHA, ANOS_CONVENIO, NOME, PLANO_NUMEROANS) VALUES (152025, 1, 'VITOR', 456);
INSERT INTO tb_cliente (CARTEIRINHA, ANOS_CONVENIO, NOME, PLANO_NUMEROANS) VALUES (253035, 4, 'ARNALDO', 123);
INSERT INTO tb_cliente (CARTEIRINHA, ANOS_CONVENIO, NOME, PLANO_NUMEROANS) VALUES (354045, 7, 'TAIS', 456);
INSERT INTO tb_cliente (CARTEIRINHA, ANOS_CONVENIO, NOME, PLANO_NUMEROANS) VALUES (455055, 0, 'LUIZ', 456);